image: python:3.7

stages:
  - test
  - lint
  - types
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run pytest

Python Code Lint:
  stage: lint
  script:
    - poetry run black .

Static Type check:
  stage: types
  script:
    - poetry run mypy .

Deploy:
  stage: deploy
  script:
    - echo "Insert deployment script here"
