image: python:3.7

stages:
  - test
  - check
  - deploy

before_script:
  - test -e $HOME/.poetry/bin/ || curl -sSL curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="$PATH:$HOME/.local/bin/"
  - poetry config virtualenvs.create false
  - rm -f poetry.lock
  - pip install --upgrade pip
  - poetry install

Unit test:
  stage: test
  script:
    - pytest ./tests/

Python Code Lint:
  stage: check
  script:
    - black .

Static Type:
  stage: check
  script:
    - mypy . --exclude 'setup\.py$'
    # We can remove the flag once this is resolved https://github.com/pypa/setuptools/issues/2345

Publish to pypi and update repository:
  stage: deploy
  script:
    - poetry version ${BUMP_RULE}
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
    - git add pyproject.toml
    - git commit -m "Bump version"
    - git remote add local https://${ACCESS_TOKEN_NAME}:${ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git && git push -o ci.skip local HEAD:master && poetry publish --build --username ${PYPI_USER} --password ${PYPI_PASSWORD}
  only:
    - master
