[tool.poetry]
name = "alibylite"
version = "0.0.1"
description = "Process and analyse live-cell imaging data"
authors = ["Alan Munoz", "Peter Swain <peter.swain@ed.ac.uk>"]
packages = [
    { include = "aliby", from="src" },
    { include = "extraction", from="src" },
    { include = "agora", from="src" },
    { include = "postprocessor", from="src" },
    { include = "logfile_parser", from="src" },
]
readme = "README.md"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
numpy = ">=1.21.6"
pandas = ">=2.0.3"
scikit-learn = ">=1.0.2, <1.3"
scipy = ">=1.7.3"
scikit-image = ">=0.18.1"

bottleneck = ">=1.3.5"
dask = ">=2021.12.0"
flatten-dict = ">=0.4.2"
h5py = ">=3.8.0"
more-itertools = ">=10.2.0"
pathos = ">=0.2.8"
pyyaml = ">=6.0.1"
py-find-1st = ">=1.1.6"
tqdm = ">=4.62.3"
xmltodict = ">=0.13.0"
zarr = ">=2.14.0"

tensorflow = "2.13.1"
baby-seg = ">=0.30.4"

[tool.poetry.extras]
omero-py = { version = ">=5.6.2", optional = true }

[tool.black]
line-length = 79
