[tool.poetry]
name = "aliby"
version = "0.1.65"
description = "Process and analyse live-cell imaging data"
authors = ["Alan Munoz", "Peter Swain <peter.swain@ed.ac.uk>"]
packages = [
    { include = "aliby", from="src" },
    { include = "extraction", from="src" },
    { include = "agora", from="src" },
    { include = "postprocessor", from="src" },
    { include = "logfile_parser", from="src" },
]
readme = "README.md"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
numpy = "<2"
scikit-learn = ">=1.0.2, <1.3"
scipy = ">=1.7.3"
scikit-image = ">=0.18.1"

dask = ">=2021.12.0"
flatten-dict = ">=0.4.2"
h5py = ">=3.8.0"
more-itertools = ">=10.2.0"
pathos = ">=0.2.8"
pyyaml = ">=5.3.1"
py-find-1st = ">=1.1.6"
tqdm = ">=4.62.3"
xmltodict = ">=0.13.0"
zarr = ">=2.14.0"

# tensorflow = "2.13.1" # TODO Check if removing this breaks baby; it was necessary for compat with cp_measure/cp-library
tensorflow = {version = ">=2.13.1", optional=true}
baby-seg = {version = ">=0.30.4", optional=true}

omero-py = { version = ">=5.6.2", optional = true }
cellpose = "^3.0.9"
polars = ">=1.5.0"
pyarrow = ">=15.0.1"
cp-measure = "^0.1.7"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
jupytext = "^1.15.2"
ipdb = "^0.13.13"
ruff = ">=0.3.2"
ruff-lsp = ">=0.0.52"

[tool.poetry.extras]
omero = ["omero-py"]
# cellpose = ["cellpose"]
# baby = ["baby-seg"]

[tool.black]
line-length = 79
